service: express-app-health
useDotenv: true

provider:
    name: aws #Define the cloud provider to use
    runtime: nodejs14.x
    stage: dev
    region: ap-southeast-1
    lambdaHashingVersion: 20201221

functions:
    app:
        handler: app.handler
        events: #Define the events that trigger the lambda
            - http: #Define an HTTP endpoint that respond to the / route
                  path: /
                  method: ANY #Define the HTTP methods to be used (GET/POST)
                  cors: true
            - http: #Define an HTTP endpoint that respond to any routes
                  path: /{proxy+}
                  method: ANY
                  cors: true
# secret key c9duWM9qxEu+qNRMJb9jVGf53qbeOLuvP6oXAPHI
# access key AKIAQYIQSBJJVFNQ4DLH

